# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enabled: true
  redis-manager:
    host: 8.131.240.13:6379

server:
  port: 8081

huang:
  jwt:
    #加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #token有效期 7天  单位秒
    expire: 604800
    header: Authorization